// tslint:disable
/**
 * Stackdriver Error Reporting
 * Groups and counts similar errors from cloud services and applications, reports new errors, and provides access to error groups and their associated errors. 
 *
 * OpenAPI spec version: v1beta1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
